package org.vaadin.stepbystep;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PersonEditorDesign extends VerticalLayout {
    protected TextField firstName;
    protected TextField lastName;
    protected TextField email;
    protected DateField dateOfBirth;
    protected TextArea notes;
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public PersonEditorDesign() {
        Design.read(this);
    }
}
